FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse" >/etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse" >>/etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse" >>/etc/apt/sources.list \
    && echo "deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse" >>/etc/apt/sources.list \
    && apt-get update

# 安装常用依赖
RUN apt-get update && apt-get install -y \
    zip \
    curl \
    wget \
    supervisor \
    apt-utils \
    curl \
    git \
    apt-transport-https \
    software-properties-common \
    g++ \
    build-essential 

# 安装常用工具 
RUN apt-get update && apt-get install -y vim wget git inetutils-ping net-tools openssh-server zsh lsof tcpdump telnet 

# Install PHP
RUN apt-get update && apt-get install -y \
    libgd-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    tzdata \
    unzip

RUN add-apt-repository -y ppa:ondrej/php

RUN apt-get update

RUN apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
    php-pear \
    php8.1 \
    php8.1-common \
    php8.1-mbstring \
    php8.1-dev \
    php8.1-xml \
    php8.1-cli \
	php8.1-mysql \
	php8.1-sqlite3 \
    php8.1-mbstring \
    php8.1-curl \
    php8.1-gd \
    php8.1-imagick \
    php8.1-xdebug \
    php8.1-xml \
    php8.1-zip \
    php8.1-odbc \
    php8.1-opcache \
    php8.1-redis \
    php8.1-bcmath\
    autoconf \
    zlib1g-dev \
    libapache2-mod-php8.1

# 安装Yaf扩展
RUN pecl install yaf \
    && echo "extension=yaf.so" >> /etc/php/8.1/fpm/php.ini

# 安装php-fpm
RUN apt-get install -y php8.1-fpm

# 安装Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# 设置默认shell
RUN chsh -s /bin/zsh

# 安装 Nginx
RUN apt-get update && apt-get install -y nginx

# 删除默认站点配置 
RUN rm -rf /etc/nginx/sites-enabled/default

# 拷贝应用站点配置文件
COPY app.conf /etc/nginx/sites-enabled/app.conf

# 安装一些有用的zsh插件
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting


# Nginx配置  
COPY app.conf /etc/nginx/sites-available/app.conf

# 设置工作目录、时区
WORKDIR /app

COPY start.sh /app

# 授予执行权限
RUN chmod +x /app/start.sh  

# PHP-FPM权限
RUN export PATH=$PATH:/usr/sbin

RUN mkdir -p /run/php

# php demo file
COPY index.php /app

# 暴露端口
EXPOSE 80 443

# 容器启动时运行脚本
CMD ["/app/start.sh"]