FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

# UPDATE PACKAGES
RUN apt-get update

# INSTALL SYSTEM UTILITIES
RUN apt-get install -y \
    apt-utils \
    curl \
    git \
    apt-transport-https \
    software-properties-common \
    g++ \
    build-essential 


RUN add-apt-repository -y ppa:ondrej/php

RUN apt-get update

RUN apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
    php-pear \
    php8.1 \
    php8.1-common \
    php8.1-mbstring \
    php8.1-dev \
    php8.1-xml \
    php8.1-cli \
	php8.1-mysql \
	php8.1-sqlite3 \
    php8.1-mbstring \
    php8.1-curl \
    php8.1-gd \
    php8.1-imagick \
    php8.1-xdebug \
    php8.1-xml \
    php8.1-zip \
    php8.1-odbc \
    php8.1-opcache \
    php8.1-redis \
    autoconf \
    zlib1g-dev \
    libapache2-mod-php8.1

RUN pecl install yaf \
    && echo "extension=yaf.so" >> /etc/php/8.1/cli/php.ini

RUN apt-get install -y php8.1-fpm
    
CMD ["php", "-v"]